### PR TITLE
Intial setup

### PR DESCRIPTION
**Pull request by Emoun**
Copies the simulator from the patmos repository and sets it up with Travis-ci.

### CODE REVIEW

**Comment by schoeberl** [comment]
I am wondering why the change in the README is shown so big in GitHub (all lines changed). Is there a CRLF issue?

**Comment by Emoun** [comment]
The README in this repo only has 2 lines that you put in initially. I have copied the simulator README into it now, so makes sense git sees it as changes. The contents are the same, though reformatted a bit for markdown and updated as I have seen fit.

**Comment by Emoun** [comment]
I should probably also mention that I don't have write permission to this repository, so can't push code to it on my own or merge this PR.

**Comment by schoeberl** [comment]
When you look at the change log https://github.com/t-crest/patmos-simulator/pull/1/commits/d7a6562fd2bf13d8a7a890fa3b5704c239a57409 <https://github.com/t-crest/patmos-simulator/pull/1/commits/d7a6562fd2bf13d8a7a890fa3b5704c239a57409>

you see 293 lines removed and 310 added. I don’t understand.

Martin

PS: Need to teach now, will fix your write access afterwards.

**Comment by Emoun** [comment]
Ah, I don't know whether there was also a CRLF issue, as git should handle that I think. But in that commit I made many small changes to the format of the README to use markdown better. I also added a section on how to install the simulator from prebuilt binaries (deployed by travis) and rearranged some of the sections.
But all the old information that was in the README is still there, just moved/edited slightly.

**Review by schoeberl — APPROVED** [review]
LGTM

**Comment by schoeberl** [comment]
The new repo was not in the developer team (where you are). Have fixed this, so you should now be in.

Cheers
Martin

**Pull request merged**
