### PR TITLE
Added --permissive-dual-issue flag

### LINKED ISSUE #17: -h gives conflicting information regarding default data cache kind
When running `pasim -h` the following is printed regarding the data cache kind:

```
-D [ --dckind ] arg (=dm)             kind of direct mapped/fully-/set-associ
                                        ative data cache, defaults to lru2
                                        (ideal, no, dm, lru[N], fifo[N])
```

The `(=dm)` should signify that a direct mapping is used when the flag is not set, however the description then says `defaults to lru2`.

Running some tests, it seems to me that direct mapping is indeed the default when the flag is not set.
We should decide which kind should be default and correct the message to fit.

### PR DESCRIPTION
**Pull request by Emoun**
'--permissive-dual-issue' flag is meant to test the effect of allowing some instructions of the instructions currently disallowed in the second issue slot.

Currently this enables loads, stores, and branches in the second issue slot with the following requirement:
Only 1 instructions of each kind may be enabled in a bundle, i.e., if there are two loads in a bundle an error will be thrown if they are both enabled. This "check" is done in the simulator at runtime and is thus a guarantee the programmer/compiler provides. The idea is the hardware can treat a violation as undefined behavior (i.e., hardware can do whatever it wants).

I have chosen to allow a store and a load to be enabled in the same bundle. This is assuming the load and store hardware is separate and may be able to execute a load and a store simultaneously , which does seem to be common but I haven't checked whether Patmos can easily implement this.

Also fixed #17

### CODE REVIEW

**Comment by schoeberl** [comment]
OK, good idea. However, I would not allow a load and store both enabled. This is hard to support in hardware.

**Comment by Emoun** [comment]
Ok, I'll disallow store and load together.

**Comment by Emoun** [comment]
I have added 2 more cases to the bundling:

1) Disallow 2 main-memory targeting instructions. E.g., cannot do a data-cache load and a call the call must fetch instruction and the cache might miss.
2) Disallow 2 stack operations like in #25 (this is a temporary solution until that issue is decided)

Question: Does it make sense to allow a stack load/store with, e.g., a call (even if the call will need to load memory)? This is currently allowed

**Comment by schoeberl** [comment]
Probably not good to mix a load with a call.Cheers,MartinOn 7 Sep 2023, at 12.16, Emad Jacob Maroun ***@***.***> wrote:﻿
I have added 3 more cases to the bundling:

Disallow 2 main-memory targeting instructions. E.g., cannot do a data-cache load and a call the call must fetch instruction and the cache might miss.
Disallow 2 stack operations like in #25 (this is a temporary solution until that issue is decided)

Question: Does it make sense to allow a stack load/store with, e.g., a call (even if the call will need to load memory)? This is currently allowed

**Comment by Emoun** [comment]
What do you mean by "not good"? Are there any hardware limitations you can think of?
The compiler could take advantage of allowing it.

**Comment by schoeberl** [comment]
As you correctly stated that a call needs to access memory (for the function size) and a load don’t work together.

Martin

**Comment by Emoun** [comment]
But here we are talking about only stack load/stores, which don't touch main memory, so no contention there.

**Comment by schoeberl** [comment]
You are right.

**Comment by Emoun** [comment]
Ok, I will keep the rules and requirements as is right now.

Also, commented out code as specified in #28 .

**Pull request merged**
